import os
from typing import List, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field
from dotenv import load_dotenv
from starlette.status import HTTP_500_INTERNAL_SERVER_ERROR
from fastapi.openapi.utils import get_openapi

# Attempt to import OpenAI SDK; provide graceful error if unavailable at runtime.
OPENAI_IMPORT_ERROR: Optional[Exception] = None
try:
    # New style client (openai>=1.0.0)
    from openai import OpenAI  # type: ignore
except Exception as e:  # pragma: no cover - graceful handling
    OpenAI = None  # type: ignore
    OPENAI_IMPORT_ERROR = e

# Load .env file if present (non-fatal if missing)
load_dotenv()

# Color theme: "Ocean Professional"
THEME = {
    "name": "Ocean Professional",
    "primary": "#2563EB",   # blue-600
    "secondary": "#F59E0B", # amber-500
    "success": "#F59E0B",   # using amber as accent success
    "error": "#EF4444",     # red-500
    "background": "#f9fafb",
    "surface": "#ffffff",
    "text": "#111827",
    "gradient": "linear-gradient(135deg, rgba(59,130,246,0.10), rgba(249,250,251,1))"
}

# PUBLIC_INTERFACE
class ChatMessage(BaseModel):
    """Represents a single chat message with role and content."""
    role: str = Field(..., description="Role of the message sender. One of: 'user', 'assistant', or 'system'.", examples=["user"])
    content: str = Field(..., description="The textual content of the message.", examples=["Hello!"])

# PUBLIC_INTERFACE
class ChatRequest(BaseModel):
    """Request body for sending chat messages to the assistant."""
    messages: List[ChatMessage] = Field(..., description="Ordered list of chat messages forming the conversation history.")
    model: Optional[str] = Field(default=None, description="Optional OpenAI chat model to use. Defaults via env MODEL_FALLBACK.")
    temperature: Optional[float] = Field(default=0.7, ge=0.0, le=2.0, description="Sampling temperature for response.")
    top_p: Optional[float] = Field(default=1.0, ge=0.0, le=1.0, description="Nucleus sampling parameter.")
    max_tokens: Optional[int] = Field(default=512, ge=1, description="Maximum tokens for the assistant response.")

# PUBLIC_INTERFACE
class ChatResponse(BaseModel):
    """Response body containing the assistant message."""
    message: ChatMessage = Field(..., description="The assistant's message as generated by the model.")
    model: str = Field(..., description="The model used to generate the response.")
    usage_prompt_tokens: Optional[int] = Field(None, description="Prompt tokens used (if available).")
    usage_completion_tokens: Optional[int] = Field(None, description="Completion tokens used (if available).")
    usage_total_tokens: Optional[int] = Field(None, description="Total tokens used (if available).")

# PUBLIC_INTERFACE
class HealthResponse(BaseModel):
    """Health check response."""
    status: str = Field(..., description="Service status string.")
    openai_ready: bool = Field(..., description="Whether OpenAI client can be initialized (API key present and SDK import OK).")

# PUBLIC_INTERFACE
class DocsTheme(BaseModel):
    """Theme configuration exposed via docs-theme endpoint."""
    name: str = Field(..., description="Theme name")
    primary: str = Field(..., description="Primary color (hex)")
    secondary: str = Field(..., description="Secondary color (hex)")
    success: str = Field(..., description="Success color (hex)")
    error: str = Field(..., description="Error color (hex)")
    background: str = Field(..., description="Background color (hex)")
    surface: str = Field(..., description="Surface color (hex)")
    text: str = Field(..., description="Text color (hex)")
    gradient_css: str = Field(..., description="Gradient CSS value used in docs header backgrounds")


def get_settings():
    """Internal settings accessor to read environment variables and validate configuration."""
    api_key = os.getenv("OPENAI_API_KEY")
    base_url = os.getenv("OPENAI_BASE_URL")  # Optional override (e.g., Azure/OpenAI-compatible gateways)
    model_fallback = os.getenv("MODEL_FALLBACK", "gpt-4o-mini")
    site_url = os.getenv("SITE_URL")  # Optional, documented for completeness

    return {
        "api_key": api_key,
        "base_url": base_url,
        "model_fallback": model_fallback,
        "site_url": site_url,
    }


def create_openai_client(settings: dict):
    """
    Internal helper to create an OpenAI client using environment variables.
    Raises HTTP 500 if SDK missing or key absent.
    """
    if OPENAI_IMPORT_ERROR or OpenAI is None:
        raise HTTPException(
            status_code=HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"OpenAI SDK import error: {str(OPENAI_IMPORT_ERROR) if OPENAI_IMPORT_ERROR else 'Unknown import failure'}",
        )
    if not settings.get("api_key"):
        raise HTTPException(
            status_code=HTTP_500_INTERNAL_SERVER_ERROR,
            detail="OPENAI_API_KEY is not set. Please configure it in the environment.",
        )

    # Construct client with optional base_url
    client = OpenAI(api_key=settings["api_key"], base_url=settings["base_url"] or None)
    return client


# Initialize FastAPI app with metadata for OpenAPI
app = FastAPI(
    title="Ocean Professional Chat API",
    description=(
        "A modern FastAPI backend providing REST endpoints to chat with an AI assistant. "
        "Styled with the Ocean Professional theme (blue and amber accents)."
    ),
    version="1.0.0",
    contact={
        "name": "Chat API",
        "url": "https://example.com",
    },
    license_info={
        "name": "MIT",
    },
    openapi_tags=[
        {
            "name": "Meta",
            "description": "Service health and documentation utilities.",
        },
        {
            "name": "Chat",
            "description": "Endpoints to send messages and receive AI-generated responses.",
        },
    ],
)

# CORS for development convenience
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict this list
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def ocean_openapi_schema():
    """
    Generate an OpenAPI schema and inject Ocean Professional branding via CSS in Swagger UI.
    We will override the default docs to apply custom CSS and a polished look.
    """
    if app.openapi_schema:
        return app.openapi_schema
    openapi_schema = get_openapi(
        title=app.title,
        version=app.version,
        description=app.description,
        routes=app.routes,
    )
    app.openapi_schema = openapi_schema
    return app.openapi_schema


app.openapi = ocean_openapi_schema  # type: ignore


# PUBLIC_INTERFACE
@app.get("/", response_model=HealthResponse, summary="Health Check", tags=["Meta"])
def health_check() -> HealthResponse:
    """
    Check if the service is running and whether the OpenAI client can be created.

    Returns:
        HealthResponse: A status message and OpenAI readiness flag.
    """
    settings = get_settings()
    openai_ready = bool(settings.get("api_key") and OpenAI is not None and OPENAI_IMPORT_ERROR is None)
    return HealthResponse(status="healthy", openai_ready=openai_ready)


# PUBLIC_INTERFACE
@app.get("/docs-theme", response_model=DocsTheme, summary="Docs Theme", tags=["Meta"])
def docs_theme() -> DocsTheme:
    """
    Retrieve the Ocean Professional theme used for API docs and example UI.

    Returns:
        DocsTheme: Color tokens for clients to mirror docs theme.
    """
    return DocsTheme(
        name=THEME["name"],
        primary=THEME["primary"],
        secondary=THEME["secondary"],
        success=THEME["success"],
        error=THEME["error"],
        background=THEME["background"],
        surface=THEME["surface"],
        text=THEME["text"],
        gradient_css=THEME["gradient"],
    )


# PUBLIC_INTERFACE
@app.get("/docs/ocean", response_class=HTMLResponse, summary="Ocean Docs UI", tags=["Meta"])
def ocean_docs() -> HTMLResponse:
    """
    A minimal Ocean Professional themed static page that points to Swagger UI and OpenAPI JSON.
    This is not a replacement for /docs but provides a custom-styled landing page.
    """
    html = f"""
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Ocean Professional - API Docs</title>
        <style>
            :root {{
                --primary: {THEME['primary']};
                --secondary: {THEME['secondary']};
                --bg: {THEME['background']};
                --surface: {THEME['surface']};
                --text: {THEME['text']};
                --error: {THEME['error']};
            }}
            body {{
                margin: 0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica Neue, Arial;
                color: var(--text);
                background: {THEME['gradient']};
                min-height: 100vh;
            }}
            .container {{
                max-width: 960px; margin: 3rem auto; padding: 2rem;
                background: var(--surface);
                border-radius: 16px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.06);
                border: 1px solid rgba(17,24,39,0.06);
            }}
            .title {{
                display:flex; align-items:center; gap:0.75rem; margin:0 0 0.5rem 0;
                font-weight: 800; letter-spacing: -0.02em;
                color: var(--primary);
            }}
            .subtitle {{
                color: #374151; margin: 0 0 1.25rem 0;
            }}
            .badge {{
                display:inline-block; padding: 0.25rem 0.6rem; border-radius: 9999px; font-size: 0.75rem;
                background: rgba(37,99,235,0.08); color: var(--primary); border:1px solid rgba(37,99,235,0.15);
            }}
            .card {{
                margin-top: 1.25rem; padding: 1rem; border-radius: 12px; background: var(--bg); border:1px solid rgba(17,24,39,0.06);
            }}
            .links {{
                display:flex; gap: 0.75rem; margin-top: 1rem; flex-wrap: wrap;
            }}
            .btn {{
                padding: 0.6rem 0.9rem; border-radius: 10px; text-decoration: none; font-weight: 600; transition: all .2s ease;
                border: 1px solid transparent;
            }}
            .btn.primary {{
                background: var(--primary); color: white;
                box-shadow: 0 6px 16px rgba(37,99,235,0.25);
            }}
            .btn.primary:hover {{
                filter: brightness(1.05);
                transform: translateY(-1px);
            }}
            .btn.secondary {{
                background: rgba(245,158,11,0.12); color: var(--secondary); border-color: rgba(245,158,11,0.25);
            }}
            .btn.secondary:hover {{
                background: rgba(245,158,11,0.18);
                transform: translateY(-1px);
            }}
            code {{
                background: rgba(17,24,39,0.05); padding: 0.15rem 0.35rem; border-radius: 6px;
            }}
        </style>
    </head>
    <body>
        <main class="container">
            <div class="badge">Ocean Professional</div>
            <h1 class="title">Chat API</h1>
            <p class="subtitle">A clean, modern FastAPI backend with OpenAI integration.</p>
            <div class="card">
                <p>OpenAPI schema: <code>/openapi.json</code></p>
                <div class="links">
                    <a class="btn primary" href="/docs">Open Swagger UI</a>
                    <a class="btn secondary" href="/redoc">Open ReDoc</a>
                </div>
            </div>
            <div class="card">
                <strong>Environment variables</strong>
                <ul>
                    <li><code>OPENAI_API_KEY</code> (required)</li>
                    <li><code>OPENAI_BASE_URL</code> (optional) - set for OpenAI-compatible endpoints</li>
                    <li><code>MODEL_FALLBACK</code> (optional, default: gpt-4o-mini)</li>
                    <li><code>SITE_URL</code> (optional, used for linking and future features)</li>
                </ul>
            </div>
        </main>
    </body>
    </html>
    """.strip()
    return HTMLResponse(content=html)


def _convert_messages_for_openai(messages: List[ChatMessage]) -> List[dict]:
    """
    Convert Pydantic ChatMessage list to OpenAI-compatible message dicts.
    """
    converted = []
    for m in messages:
        role = m.role.lower().strip()
        if role not in {"system", "user", "assistant"}:
            raise HTTPException(status_code=422, detail=f"Invalid role '{m.role}'. Must be one of: system, user, assistant.")
        converted.append({"role": role, "content": m.content})
    return converted


# PUBLIC_INTERFACE
@app.post(
    "/chat",
    response_model=ChatResponse,
    summary="Send chat messages",
    description="Send conversation messages and receive an AI-generated assistant response using OpenAI.",
    tags=["Chat"],
    responses={
        200: {"description": "AI response generated successfully."},
        422: {"description": "Validation error for request payload or message roles."},
        500: {"description": "Server error (missing configuration or OpenAI SDK not available)."},
    },
)
def chat(request: ChatRequest) -> ChatResponse:
    """
    Generate an AI response to the provided conversation messages using OpenAI Chat Completions.

    Parameters:
        request (ChatRequest): Conversation history and optional generation parameters.

    Returns:
        ChatResponse: Assistant response message and optional usage metrics.
    """
    settings = get_settings()
    client = create_openai_client(settings)

    model = request.model or settings["model_fallback"] or "gpt-4o-mini"
    payload_messages = _convert_messages_for_openai(request.messages)

    try:
        # Using the new OpenAI Python SDK interface (>=1.0.0)
        completion = client.chat.completions.create(
            model=model,
            messages=payload_messages,
            temperature=request.temperature,
            top_p=request.top_p,
            max_tokens=request.max_tokens,
        )
    except Exception as e:
        raise HTTPException(status_code=HTTP_500_INTERNAL_SERVER_ERROR, detail=f"OpenAI chat completion failed: {str(e)}")

    # Extract the assistant message and usage (if present)
    try:
        choice = completion.choices[0]
        assistant_content = choice.message.content or ""
        usage = getattr(completion, "usage", None)
        prompt_tokens = getattr(usage, "prompt_tokens", None) if usage else None
        completion_tokens = getattr(usage, "completion_tokens", None) if usage else None
        total_tokens = getattr(usage, "total_tokens", None) if usage else None
    except Exception:
        assistant_content = ""
        prompt_tokens = completion_tokens = total_tokens = None

    return ChatResponse(
        message=ChatMessage(role="assistant", content=assistant_content),
        model=model,
        usage_prompt_tokens=prompt_tokens,
        usage_completion_tokens=completion_tokens,
        usage_total_tokens=total_tokens,
    )
